/* ============================================================
   ORTO — dati: menù del giorno + ricette vegetariane
   Tutto in italiano. Nessuna connessione necessaria.
   ============================================================ */

/* ---------- MENÙ DEL GIORNO (ruota ogni giorno) ---------- */
const MENU_GIORNO = [
  { tema: "Lunedì mediterraneo", colazione: "Yogurt greco con miele, noci e fichi", pranzo: "Bowl di ceci e peperoni arrostiti con farro", cena: "Parmigiana di melanzane al basilico", spuntino: "Olive, cetriolo e feta" },
  { tema: "Verde dell'orto", colazione: "Uova strapazzate con spinaci e funghi", pranzo: "Tabbouleh di lenticchie alla menta", cena: "Peperoni ripieni di riso ed erbe", spuntino: "Mela a fette con crema di mandorle" },
  { tema: "Giornata comfort", colazione: "Pancake di banana e avena", pranzo: "Zuppa cremosa di pomodoro e cannellini", cena: "Risotto ai funghi con parmigiano", spuntino: "Cioccolato fondente e nocciole" },
  { tema: "Fresco e luminoso", colazione: "Pane tostato con avocado e peperoncino", pranzo: "Insalata di halloumi e anguria", cena: "Curry di verdure al cocco con riso", spuntino: "Yogurt con mango e lime" },
  { tema: "Domenica lenta", colazione: "Shakshuka con pane croccante", pranzo: "Pasta con zucca arrosto e salvia", cena: "Cannelloni ricotta e spinaci", spuntino: "Ceci croccanti al forno" },
  { tema: "Ispirazione asiatica", colazione: "Avena al miso con sesamo e cipollotto", pranzo: "Noodles soba con tofu ed edamame", cena: "Riso saltato con verdure e uovo", spuntino: "Edamame al vapore con sale" },
  { tema: "Cucina rustica", colazione: "Pane integrale con ricotta e pomodoro", pranzo: "Minestrone con crosta di parmigiano", cena: "Frittata di patate e rosmarino", spuntino: "Bastoncini di carota con hummus" },
  { tema: "Ricco di proteine", colazione: "Fiocchi di latte con frutti di bosco e semi", pranzo: "Bowl di quinoa, fagioli neri e avocado", cena: "Paneer tikka con riso di cavolfiore", spuntino: "Yogurt greco con semi di zucca" },
  { tema: "Caldo e speziato", colazione: "Porridge speziato al chai con pera", pranzo: "Dahl di lenticchie e patata dolce", cena: "Tajine di verdure speziate con couscous", spuntino: "Mandorle speziate tostate" },
  { tema: "Tavola italiana", colazione: "Caffè e pane con ricotta e arancia", pranzo: "Caprese con pomodori cuore di bue", cena: "Tagliatelle ai funghi porcini", spuntino: "Grissini con tapenade di olive" },
  { tema: "Mercato fresco", colazione: "Smoothie bowl con granola", pranzo: "Insalata di barbabietola, caprino e rucola", cena: "Quesadillas di zucchine e mais", spuntino: "Frutta fresca e una manciata di noci" },
  { tema: "Raccolto generoso", colazione: "Pane tostato con funghi e timo", pranzo: "Orzo con verdure arrosto e feta", cena: "Chili di fagioli e verdure", spuntino: "Formaggio, cracker e uva" },
];

/* ---------- RICETTE CASUALI / RICERCABILI ----------
   Ogni ingrediente ha 'key' = parole chiave per il match.       */
const RICETTE = [
  {
    titolo: "Orzo al limone ed erbe in padella",
    sottotitolo: "Cremoso, profumato e pronto in mezz'ora",
    tags: ["cereali", "comfort"],
    tempo: "30 min", porzioni: 4,
    ingredienti: [
      { t: "300 g di orzo (pasta)", key: ["orzo", "pasta", "cereali"] },
      { t: "1 porro affettato", key: ["porro", "cipolla"] },
      { t: "2 spicchi d'aglio", key: ["aglio"] },
      { t: "1 limone (scorza + succo)", key: ["limone"] },
      { t: "150 g di spinaci", key: ["spinaci"] },
      { t: "60 g di parmigiano grattugiato", key: ["parmigiano", "formaggio"] },
      { t: "Aneto fresco, olio, sale e pepe", key: ["aneto", "olio"] },
    ],
    passi: [
      "Fai appassire porro e aglio nell'olio per 5 minuti.",
      "Aggiungi l'orzo, poi 750 ml di acqua calda un mestolo alla volta, mescolando, finché è tenero (circa 12 min).",
      "Unisci gli spinaci fino ad appassirli, poi scorza, succo di limone e parmigiano.",
      "Aggiusta di sale e completa con l'aneto.",
    ],
  },
  {
    titolo: "Tacos di fagioli neri affumicati",
    sottotitolo: "Tacos veloci con un tocco affumicato",
    tags: ["legumi", "speziato"],
    tempo: "25 min", porzioni: 3,
    ingredienti: [
      { t: "2 lattine di fagioli neri", key: ["fagioli", "fagioli neri", "legumi"] },
      { t: "1 cucchiaino di paprika affumicata", key: ["paprika"] },
      { t: "1 cucchiaino di cumino", key: ["cumino"] },
      { t: "1 cipolla rossa", key: ["cipolla"] },
      { t: "8 tortillas piccole", key: ["tortilla", "tortillas", "pane"] },
      { t: "1 avocado", key: ["avocado"] },
      { t: "Lime e coriandolo", key: ["lime", "coriandolo"] },
    ],
    passi: [
      "Rosola la cipolla a fette, aggiungi i fagioli e le spezie con un goccio d'acqua.",
      "Schiaccia leggermente e fai sobbollire 6–8 minuti fino ad addensare.",
      "Scalda le tortillas in padella asciutta.",
      "Farcisci con fagioli, avocado a fette, lime e coriandolo.",
    ],
  },
  {
    titolo: "Curry di ceci al cocco",
    sottotitolo: "Un curry in 20 minuti dal gusto lungo",
    tags: ["legumi", "speziato"],
    tempo: "20 min", porzioni: 4,
    ingredienti: [
      { t: "2 lattine di ceci", key: ["ceci", "legumi"] },
      { t: "1 lattina di latte di cocco", key: ["latte di cocco", "cocco"] },
      { t: "2 cucchiai di pasta di curry", key: ["curry"] },
      { t: "1 cipolla", key: ["cipolla"] },
      { t: "2 spicchi d'aglio", key: ["aglio"] },
      { t: "Un pezzo di zenzero", key: ["zenzero"] },
      { t: "200 g di spinaci", key: ["spinaci"] },
      { t: "Riso, per servire", key: ["riso"] },
    ],
    passi: [
      "Fai appassire cipolla, aglio e zenzero, poi unisci la pasta di curry per 1 minuto.",
      "Aggiungi ceci e latte di cocco; sobbolli 12 minuti.",
      "Fai appassire gli spinaci e aggiusta di sale.",
      "Servi sul riso al vapore.",
    ],
  },
  {
    titolo: "Torta salata cipolle caramellate e caprino",
    sottotitolo: "Sembra elaborata, ma è facilissima",
    tags: ["uova", "comfort"],
    tempo: "45 min", porzioni: 4,
    ingredienti: [
      { t: "1 rotolo di pasta sfoglia", key: ["sfoglia", "pasta sfoglia", "pasta"] },
      { t: "3 cipolle grandi affettate", key: ["cipolla"] },
      { t: "1 cucchiaio di aceto balsamico", key: ["aceto", "balsamico"] },
      { t: "100 g di caprino morbido", key: ["caprino", "formaggio"] },
      { t: "1 cucchiaino di timo", key: ["timo"] },
      { t: "1 uovo (per spennellare)", key: ["uovo", "uova"] },
      { t: "Miele q.b.", key: ["miele"] },
    ],
    passi: [
      "Cuoci le cipolle a fuoco basso 20 min, poi unisci il balsamico.",
      "Incidi un bordo sulla sfoglia e distribuisci le cipolle all'interno.",
      "Aggiungi caprino e timo, spennella il bordo con l'uovo.",
      "Inforna a 200°C per 20 min, poi irrora di miele.",
    ],
  },
  {
    titolo: "Bowl di halloumi e verdure arrosto",
    sottotitolo: "Halloumi dorato e salato su cereali caldi",
    tags: ["cereali", "leggero"],
    tempo: "35 min", porzioni: 2,
    ingredienti: [
      { t: "225 g di halloumi a fette", key: ["halloumi", "formaggio"] },
      { t: "1 zucchina", key: ["zucchina", "zucchine"] },
      { t: "1 peperone rosso", key: ["peperone", "peperoni"] },
      { t: "1 tazza di quinoa o couscous cotti", key: ["quinoa", "couscous", "cereali"] },
      { t: "2 cucchiai d'olio, origano", key: ["olio", "origano"] },
      { t: "Limone e prezzemolo", key: ["limone", "prezzemolo"] },
    ],
    passi: [
      "Arrostisci le verdure a pezzi con olio e origano a 200°C per 20 min.",
      "Rosola l'halloumi 2 minuti per lato fino a doratura.",
      "Componi cereali, verdure e halloumi nelle bowl.",
      "Completa con limone e prezzemolo.",
    ],
  },
  {
    titolo: "Zuppa cremosa di pomodoro e cannellini",
    sottotitolo: "Da dispensa, profondamente avvolgente",
    tags: ["legumi", "comfort"],
    tempo: "30 min", porzioni: 4,
    ingredienti: [
      { t: "2 lattine di pomodori a pezzi", key: ["pomodoro", "pomodori"] },
      { t: "1 lattina di fagioli cannellini", key: ["fagioli", "cannellini", "legumi"] },
      { t: "1 cipolla", key: ["cipolla"] },
      { t: "2 spicchi d'aglio", key: ["aglio"] },
      { t: "1 cucchiaio di concentrato di pomodoro", key: ["concentrato", "pomodoro"] },
      { t: "Un goccio di panna o latte di cocco", key: ["panna", "latte di cocco"] },
      { t: "Basilico, pane per servire", key: ["basilico", "pane"] },
    ],
    passi: [
      "Fai appassire cipolla e aglio, unisci il concentrato per un minuto.",
      "Aggiungi pomodori e fagioli, sobbolli 15 minuti.",
      "Frulla metà zuppa per una consistenza cremosa ma rustica, unisci la panna.",
      "Completa col basilico e servi col pane.",
    ],
  },
  {
    titolo: "Risotto ai funghi e timo",
    sottotitolo: "Il tipo di mantecatura che rilassa",
    tags: ["cereali", "comfort"],
    tempo: "40 min", porzioni: 4,
    ingredienti: [
      { t: "300 g di riso arborio", key: ["riso", "arborio"] },
      { t: "400 g di funghi misti", key: ["funghi"] },
      { t: "1 cipolla", key: ["cipolla"] },
      { t: "150 ml di vino bianco (facoltativo)", key: ["vino"] },
      { t: "1 L di brodo vegetale caldo", key: ["brodo"] },
      { t: "50 g di parmigiano", key: ["parmigiano", "formaggio"] },
      { t: "Burro e timo", key: ["burro", "timo"] },
    ],
    passi: [
      "Rosola i funghi nel burro e mettili da parte.",
      "Fai appassire la cipolla, aggiungi il riso e tostalo 1 minuto, poi il vino.",
      "Aggiungi il brodo un mestolo alla volta, mescolando, per ~18 min.",
      "Manteca con funghi, parmigiano e timo; lascia riposare 2 minuti.",
    ],
  },
  {
    titolo: "Dahl speziato di patata dolce",
    sottotitolo: "Lenticchie che ti abbracciano",
    tags: ["legumi", "speziato", "comfort"],
    tempo: "35 min", porzioni: 4,
    ingredienti: [
      { t: "250 g di lenticchie rosse", key: ["lenticchie", "legumi"] },
      { t: "1 patata dolce a cubetti", key: ["patata dolce", "patata"] },
      { t: "1 lattina di latte di cocco", key: ["latte di cocco", "cocco"] },
      { t: "1 cipolla", key: ["cipolla"] },
      { t: "2 cucchiaini di garam masala", key: ["garam masala", "spezie"] },
      { t: "1 cucchiaino di curcuma", key: ["curcuma"] },
      { t: "Aglio e zenzero", key: ["aglio", "zenzero"] },
    ],
    passi: [
      "Fai appassire cipolla, aglio, zenzero e spezie.",
      "Aggiungi lenticchie, patata dolce, latte di cocco e 500 ml d'acqua.",
      "Sobbolli 25 min finché le lenticchie si sfaldano e la patata è morbida.",
      "Aggiusta di sale e servi con riso o pane piatto.",
    ],
  },
  {
    titolo: "Avocado ripieno alla caprese",
    sottotitolo: "Senza cottura",
    tags: ["senza cottura", "leggero"],
    tempo: "10 min", porzioni: 2,
    ingredienti: [
      { t: "2 avocado maturi", key: ["avocado"] },
      { t: "150 g di pomodorini", key: ["pomodorini", "pomodoro"] },
      { t: "1 mozzarella o bocconcini", key: ["mozzarella", "formaggio"] },
      { t: "Basilico fresco", key: ["basilico"] },
      { t: "Glassa di balsamico, olio, sale", key: ["balsamico", "olio"] },
    ],
    passi: [
      "Taglia a metà e snocciola gli avocado.",
      "Taglia a dadini pomodorini e mozzarella, spezzetta il basilico.",
      "Riempi le cavità degli avocado con il composto.",
      "Irrora con olio e balsamico, sala e servi.",
    ],
  },
  {
    titolo: "Gnocchi croccanti al burro e salvia",
    sottotitolo: "Niente bollitura — si fanno croccanti in padella",
    tags: ["pasta", "comfort"],
    tempo: "20 min", porzioni: 2,
    ingredienti: [
      { t: "500 g di gnocchi di patate", key: ["gnocchi", "patata"] },
      { t: "60 g di burro", key: ["burro"] },
      { t: "10 foglie di salvia", key: ["salvia"] },
      { t: "2 spicchi d'aglio", key: ["aglio"] },
      { t: "Una manciata di piselli", key: ["piselli", "legumi"] },
      { t: "Parmigiano e limone", key: ["parmigiano", "formaggio", "limone"] },
    ],
    passi: [
      "Rosola gli gnocchi in poco olio fino a doratura e croccantezza.",
      "Aggiungi burro, salvia e aglio; lascia spumeggiare e dorare.",
      "Unisci i piselli per 2 minuti.",
      "Completa con parmigiano e una spruzzata di limone.",
    ],
  },
  {
    titolo: "Shakshuka",
    sottotitolo: "Uova in camicia in salsa speziata di pomodoro",
    tags: ["uova", "speziato"],
    tempo: "30 min", porzioni: 3,
    ingredienti: [
      { t: "2 lattine di pomodori a pezzi", key: ["pomodoro", "pomodori"] },
      { t: "1 peperone rosso", key: ["peperone", "peperoni"] },
      { t: "1 cipolla", key: ["cipolla"] },
      { t: "2 spicchi d'aglio", key: ["aglio"] },
      { t: "1 cucchiaino di cumino, 1 di paprika", key: ["cumino", "paprika"] },
      { t: "4 uova", key: ["uova", "uovo"] },
      { t: "Feta e prezzemolo", key: ["feta", "formaggio", "prezzemolo"] },
    ],
    passi: [
      "Fai appassire cipolla e peperone, aggiungi aglio e spezie.",
      "Versa i pomodori e sobbolli 10 min fino ad addensare.",
      "Crea degli incavi e rompici le uova; copri e cuoci a piacere.",
      "Cospargi di feta e prezzemolo, servi col pane.",
    ],
  },
  {
    titolo: "Noodles al sesamo e arachidi",
    sottotitolo: "Cinque minuti di salsa, comfort totale",
    tags: ["pasta", "speziato"],
    tempo: "15 min", porzioni: 2,
    ingredienti: [
      { t: "200 g di noodles", key: ["noodles", "pasta"] },
      { t: "3 cucchiai di burro d'arachidi", key: ["arachidi", "burro d'arachidi"] },
      { t: "2 cucchiai di salsa di soia", key: ["salsa di soia", "soia"] },
      { t: "1 cucchiaio di aceto di riso", key: ["aceto"] },
      { t: "1 cucchiaino di olio di sesamo", key: ["sesamo", "olio"] },
      { t: "Cipollotto e semi di sesamo", key: ["cipollotto", "sesamo"] },
      { t: "Cetriolo a julienne", key: ["cetriolo"] },
    ],
    passi: [
      "Cuoci i noodles e tieni da parte un po' d'acqua di cottura.",
      "Sbatti burro d'arachidi, soia, aceto, olio di sesamo e un cucchiaino di miele, allungando con l'acqua.",
      "Condisci i noodles con la salsa.",
      "Completa con cetriolo, cipollotto e sesamo.",
    ],
  },
  {
    titolo: "Frittata di patate e cipolla",
    sottotitolo: "La cena del 'non so cosa fare', sempre buona",
    tags: ["uova", "comfort"],
    tempo: "25 min", porzioni: 3,
    ingredienti: [
      { t: "6 uova", key: ["uova", "uovo"] },
      { t: "2 patate lessate a fette", key: ["patata", "patate"] },
      { t: "1 cipolla", key: ["cipolla"] },
      { t: "40 g di parmigiano", key: ["parmigiano", "formaggio"] },
      { t: "Prezzemolo, olio, sale e pepe", key: ["prezzemolo", "olio"] },
    ],
    passi: [
      "Rosola la cipolla e le patate in padella per 5 minuti.",
      "Sbatti le uova con parmigiano, sale e pepe.",
      "Versa sulle patate e cuoci a fuoco basso finché si rapprende.",
      "Gira (o passa sotto il grill) e completa col prezzemolo.",
    ],
  },
  {
    titolo: "Insalata di farro, feta e pomodorini",
    sottotitolo: "Pranzo fresco che regge bene il giorno dopo",
    tags: ["cereali", "leggero", "senza cottura"],
    tempo: "20 min", porzioni: 3,
    ingredienti: [
      { t: "250 g di farro cotto", key: ["farro", "cereali"] },
      { t: "150 g di pomodorini", key: ["pomodorini", "pomodoro"] },
      { t: "100 g di feta", key: ["feta", "formaggio"] },
      { t: "1 cetriolo", key: ["cetriolo"] },
      { t: "Olive, menta e limone", key: ["olive", "menta", "limone"] },
      { t: "Olio extravergine, sale", key: ["olio"] },
    ],
    passi: [
      "Taglia pomodorini, cetriolo e feta a cubetti.",
      "Unisci al farro con le olive.",
      "Condisci con olio, succo di limone e menta spezzettata.",
      "Lascia insaporire 10 minuti prima di servire.",
    ],
  },
  {
    titolo: "Peperoni ripieni di riso ed erbe",
    sottotitolo: "Colorati, sazianti, ottimi anche tiepidi",
    tags: ["cereali", "comfort"],
    tempo: "45 min", porzioni: 4,
    ingredienti: [
      { t: "4 peperoni", key: ["peperone", "peperoni"] },
      { t: "200 g di riso", key: ["riso", "cereali"] },
      { t: "1 cipolla", key: ["cipolla"] },
      { t: "100 g di feta o caprino", key: ["feta", "caprino", "formaggio"] },
      { t: "Pomodorini, prezzemolo e menta", key: ["pomodorini", "prezzemolo", "menta"] },
      { t: "Olio, sale e pepe", key: ["olio"] },
    ],
    passi: [
      "Cuoci il riso e mescolalo con cipolla rosolata, erbe, pomodorini e formaggio.",
      "Taglia la calotta ai peperoni e svuotali.",
      "Riempili col riso e disponili in teglia con un filo d'olio.",
      "Inforna a 190°C per 30 minuti.",
    ],
  },
  {
    titolo: "Pasta zucchine e ricotta",
    sottotitolo: "Cremosa senza panna, pronta nel tempo della pasta",
    tags: ["pasta", "leggero"],
    tempo: "20 min", porzioni: 3,
    ingredienti: [
      { t: "300 g di pasta", key: ["pasta"] },
      { t: "2 zucchine", key: ["zucchina", "zucchine"] },
      { t: "150 g di ricotta", key: ["ricotta", "formaggio"] },
      { t: "1 spicchio d'aglio", key: ["aglio"] },
      { t: "Scorza di limone e basilico", key: ["limone", "basilico"] },
      { t: "Olio, sale e pepe", key: ["olio"] },
    ],
    passi: [
      "Salta le zucchine a rondelle con aglio e olio finché morbide.",
      "Cuoci la pasta e tieni da parte un po' d'acqua.",
      "Manteca con la ricotta e l'acqua di cottura fino a una crema.",
      "Unisci scorza di limone e basilico.",
    ],
  },
];
